"""empty message

Revision ID: 1c69a06d235b
Revises: None
Create Date: 2014-05-20 20:25:17.053000

"""

# revision identifiers, used by Alembic.
revision = '1c69a06d235b'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product', sa.String(length=16), nullable=True),
    sa.Column('period', sa.String(length=8), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('start_hour', sa.Integer(), nullable=True),
    sa.Column('valid_start', sa.DateTime(), nullable=True),
    sa.Column('valid_end', sa.DateTime(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecasts_timestamp'), 'forecasts', ['timestamp'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forecasts_timestamp'), table_name='forecasts')
    op.drop_table('forecasts')
    op.drop_table('locations')
    ### end Alembic commands ###
